### ISSUE TITLE
☂️Spec

### ISSUE THREAD

**Issue by uetchy** [vivliostyle/vfm#1]
![Twitter Post - VFM](https://user-images.githubusercontent.com/431808/72865588-c367ea00-3d1b-11ea-9341-6dae16c5891b.png)

Custom Markdown syntax specialized in book authoring.

[**✍️Working Draft**](https://github.com/vivliostyle/vfm/blob/master/spec/vfm.md)
[**🗣Slack**](https://vivliostyle.slack.com/archives/CSJHLHN3E)

## Feedback

If you have any suggestions on adding and/or modifying stuff in the working draft, please [create an issue](https://github.com/vivliostyle/vfm/issues/new?assignees=&labels=spec&template=rfc---proposal.md&title=spec%3A+).

## References

- [CommonMark Spec](https://spec.commonmark.org/)
- [dewriteful](https://github.com/pentapod/dewriteful)
- [Digital Publishing WAI-ARIA Module 1.0](https://www.w3.org/TR/dpub-aria/)
- [env-create-book](https://github.com/akabekobeko/env-create-book)
- [GitHub Flavored Markdown Spec](https://github.github.com/gfm/)
- [LeME](https://leme.style/making-guide/point-text/)
- [Markua](http://markua.com/)
- [mdast](https://github.com/syntax-tree/mdast)
- [Pandoc's Markdown](https://pandoc.org/MANUAL.html#pandocs-markdown)
- [PHP Markdown Extra](https://michelf.ca/projects/php-markdown/extra/)
- [remark-rehype](https://github.com/remarkjs/remark-rehype)
- [remark](https://github.com/remarkjs/remark)
- [vibook](https://github.com/shunito/vibook)
- [Web Content Accessibility Guidelines (WCAG) 2.1](https://www.w3.org/TR/WCAG21/)
- [zmarkdown](https://github.com/zestedesavoir/zmarkdown)
- [でんでんマークダウン](https://conv.denshochan.com/markdown)

**Comment by uetchy** [comment]
Timeline

- 2020-01-25 - 2020-01-31: RFC - First round
- 2020-02-01 - 2020-02-07: Revise draft
- 2020-02-08 - 2020-02-14: RFC - Final round
- 2020-02-15~: Finalize draft

**Comment by akabekobeko** [comment]
# Frontmatter

Markdown (ファイル) 単位のメタデータ定義方法として Frontmatter を提案します。

## 目的

- Markdown にタイトルや著者などのメタデータを定義したい
  - Markdown 単体で文書として必要な情報を持つ
  - 索引の生成処理などで Markdown 単位のタイトルや著者を引用したい
- Markdown 単位のカスタマイズ手段がほしい
  - 章や著者ごとに外観を変更する
  - 例えば著者へ設定した値を `<body id="author">` のように反映させて CSS セレクター分岐を容易にする

## 記法

記法は著名な静的サイト ジェネレーターを踏襲します。

- [Front Matter | Jekyll • Simple, blog-aware, static sites](https://jekyllrb.com/docs/front-matter/)
- [Front Matter | Hugo](https://gohugo.io/content-management/front-matter/)
- [Adding Markdown Pages | GatsbyJS](https://www.gatsbyjs.org/docs/adding-markdown-pages/#frontmatter-for-metadata-in-markdown-files)

これらは Markdown の先頭へ主に YAML 形式 (Hugo は `+++` で定義すると TOML になる) で記述します。

```
---
property: value
---
```

プロパティーについては以下を提案します。草案なので最小です。

|Property|Type|Description|
|---|---|---|
|title|String|Markdown 文書のタイトル。Markdown 先頭の `#` をタイトルにする方法も考えられるが、必ずしもこれが定義されるとは限らないので明示的なタイトルがほしい。|
|author|String|著者。|

**Comment by akabekobeko** [comment]
For english:

# Frontmatter

Propose Frontmatter as a method of defining metadata in Markdown (file) units.

## Purpose

- I want to define metadata such as title and author in Markdown.
  - Markdown alone has necessary information as a document.
  - I want to cite titles and authors in Markdown units in index generation processing etc.
- I want a way to customize Markdown units.
  - Change appearance for each chapter or author.
  - Reflect the value set for the author, for example, as `<body id="author">`, to make CSS selector branching easier.

## Format

The notation follows the famous static site generator.

- [Front Matter | Jekyll • Simple, blog-aware, static sites](https://jekyllrb.com/docs/front-matter/)
- [Front Matter | Hugo](https://gohugo.io/content-management/front-matter/)
- [Adding Markdown Pages | GatsbyJS](https://www.gatsbyjs.org/docs/adding-markdown-pages/#frontmatter-for-metadata-in-markdown-files)

These are written at the top of Markdown mainly in YAML format (Hugo becomes TOML when defined with `+++`).

```
---
property: value
---
```

For properties, we suggest the following: Minimal because it is a draft.

|Property|Type|Description|
|---|---|---|
|title|String|Markdown The title of the document. Markdown The first `#` can be a title, but this is not always defined, so I want an explicit title.|
|author|String|Author.|

**Comment by akabekobeko** [comment]
# 基本書式と拡張書式

Markdown の HTML 変換定義において GFM(GitHub Flavored Markdown) など広く普及した書式を参考にするなら、それを基本書式として明示することを提案します。これは既存の書式へ基づく場合の提案です。そうした対象がなければ不要です。

## 目的

基本書式に対して機能拡張したものについては、拡張書式として扱うことを提案します。VFM の書式リファレンスを公開する際、ユーザーが基本と拡張を区別できることが好ましいです。

基本書式が明示されることで、少なくともその範疇であれば互換や可搬性が保証されることになります。これは他の Markdown 書式との相互変換や移行にも役立つでしょう。

**Comment by akabekobeko** [comment]
For english:

# Basic format and extended format

If refer to a widely used format such as GFM (GitHub Flavored Markdown) in the HTML conversion definition of Markdown, it is suggested to specify it as a basic format. This is a suggestion based on existing formats. It is unnecessary if there is no such object.

## Purpose

It is proposed that the extension of the basic format be treated as an extended format. When publishing a VFM format reference, it is desirable for users to be able to distinguish between basic and extended.

Specifying the basic format guarantees compatibility and portability, at least in that category. This will also help with conversion and migration to and from other Markdown formats.

**Comment by uetchy** [comment]
> If refer to a widely used format such as GFM (GitHub Flavored Markdown) in the HTML conversion definition of Markdown, it is suggested to specify it as a basic format. This is a suggestion based on existing formats. It is unnecessary if there is no such object.

VFM doesn't intend to be a superset/subset of either CommonMark or GFM because of the fundamental incompatibility with a passage handling. Rather, VFM will be a self-contained specification that derives only some of the syntax required for book writing from other dialects such as CommonMark and GFM.

**Comment by akabekobeko** [comment]
他の書式を引用しなくても、よく使われる書式をそこそこ網羅したサンプルさえあれば「だいたい GFM や CommonMark のようだ」と判断してくれそうですね。

Even if don't quote other formats, it seems that if you have a sample that covers all of the commonly used formats, it will judge that it is "generally like GFM or CommonMark".

**Comment by MurakamiShinyu** [comment]
# Pandoc's Markdown

[Pandoc’s Markdown](https://pandoc.org/MANUAL.html#pandocs-markdown) has some useful features and we should consider adopting them:

- [Tables](https://pandoc.org/MANUAL.html#tables)
- [Definition lists](https://pandoc.org/MANUAL.html#definition-lists)
- [Math](https://pandoc.org/MANUAL.html#math)
  - **Note**: Vivliostyle supports math: https://github.com/vivliostyle/vivliostyle/issues/523
- [Divs and Spans](https://pandoc.org/MANUAL.html#divs-and-spans)
  - `fenced_divs`
  - `bracketed_spans`
- [Footnotes](https://pandoc.org/MANUAL.html#footnotes)
- [Citations](https://pandoc.org/MANUAL.html#citations)

**Comment by MurakamiShinyu** [comment]
# でんでんマークダウン

(Denden Markdown)

https://conv.denshochan.com/markdown

> でんでんマークダウンの記法は [Markdown](https://daringfireball.net/projects/markdown/) の方言のひとつ [PHP Markdown Extra](http://michelf.ca/projects/php-markdown/extra/) をさらに拡張して、日本語と電子出版に最適化させたものです。

(The Denden Markdown notation is a further extension of PHP Markdown Extra, a Markdown dialect, optimized for Japanese and electronic publishing.)

でんでんマークダウンはとても参考になると思います。日本語に必要なルビや縦中横など：

- [ルビ (ruby)](https://conv.denshochan.com/markdown#ruby)
- [縦中横 (horizontal-in-vertical composition)](https://conv.denshochan.com/markdown#tcy)

ただしこの縦中横の記法（例: `昭和^53^年`）は、他のMarkdown拡張（pandocなど）では上付き文字（superscript）だったりするので、ほかの記法に変えた方がよいかもしれません。

**Comment by uetchy** [comment]
Thanks for the feedback and ideas!
After a few days, I realized that each suggestion must be separated into a single pull request so that we can comment on it directly and can merge them while maintaining the authorship.

We need additional suggestion on the following topics:

- text-combine-upright (縦中横)
- Inline notation for [walled block](https://github.com/vivliostyle/vfm/blob/master/spec/vfm.md#walled-block)

**Comment by uetchy** [comment]
vfm@next just hit [alpha.10](
https://github.com/vivliostyle/vfm/releases/tag/v1.0.0-alpha.10) and available at `next` channel in npm.

```
npm i -g @vivliostyle/vfm@next
npm i -g @vivliostyle/vfm@1.0.0-alpha.10
```

vfm@next supports [beta spec](https://github.com/vivliostyle/vfm/issues?q=is%3Aissue+is%3Aopen+label%3Astage%3Abeta) which are needed to be tested well.

Comments & **PRs** are welcome!

**Comment by akabekobeko** [comment]
@uetchy のコメントで各案を個別の issue にしようと提案されており、既にそう運用されているため本件は close します。
