### ISSUE TITLE
spec: literal and escape

### ISSUE THREAD

**Issue by kmuto** [vivliostyle/vfm#12]
## Goals

Not sure. `\char` ?

If VFM appends a special meaning to a literal character, it will be needed to add escaping rule to impress its literal.

**Comment by tk0miya** [comment]
I think following spec of CommonMark is easy to understand.
https://spec.commonmark.org/0.29/#backslash-escapes

It is well organized and has a good rule for conversion. IMO, no reason not to follow it. But VFM (draft) spec says as following:

>Not intended to be a superset/subset of either CommonMark or GFM.

I can understand VFM does not to follow GFM. Indeed, it contains some own extensions to markdown. But, on the other hand, CommonMark is not. It is a ruleset of conversion markdown document to others. Its goal is clear ruleset for markdown processors (mainly). I think following it makes VFM better and easy to make a spec for us.

Note: AFAIK, CommonMark only adds "Fenced code blocks" annotation to original markdown syntax. This is a reason I said "mainly". It's an exception of the concept of CM.

**Comment by akabekobeko** [comment]
@tk0miya さんがコメントされている時点の VFM ドラフトでは CommonMark/GFM を意図していないとしていました。しかしその後の議論で基本的に CommonMark/GFM のスーパーセットとなるよう方針転換をしました。現在の `docs/vfm.md` にその旨、記載しています。

> VFM is implemented top on CommonMark and GFM.

よって本件は CommonMark/GFM を踏襲ということで close します。議論を継続されたい場合はその旨をコメントのうえ、Reopen してください。
