### ISSUE TITLE
EPUB Canonical Fragment Identifiers

### ISSUE THREAD

**Issue by uetchy** [vivliostyle/vfm#14]
Support EPUB CFI to map structural differences between Markdown and generated HTML document.

## Refs

- http://idpf.org/epub/linking/cfi/

**Comment by akabekobeko** [comment]
提案後、特に議論されていないため v2.0 へ見送ります。

提案にあるリンク先の仕様を見るに、かなり大きな機能となりそうなので、そもそも対応するのか？から議論したいです。EPUB 変換については Vivliostyle が担えばよさそうにも思えます。興味のある方、意見ください。

**Comment by akabekobeko** [comment]
長く放置されているのでタスク整理のため close します。
