### ISSUE TITLE
Register VFM as a part of IANA Markdown Variants

### ISSUE THREAD

**Issue by uetchy** [vivliostyle/vfm#17]
https://www.iana.org/assignments/markdown-variants/markdown-variants.xhtml

**Comment by akabekobeko** [comment]
v1.0.0 がリリースされたら改めて検討予定。

**Comment by akabekobeko** [comment]
VFM を Markdown Variants として掲載リクエストするか？という話なので、前述のコメントどおり v1.0 正式リリース後にどうするかを議論しましょう。

v2.0 における remark 13 対応を見越して v1.0 では実装途中、議論中の機能を見送っているため、v2.0 リリースまで掲載リクエストを見送るというのもありです。

**Comment by akabekobeko** [comment]
長く放置されており登録予定もないので close します。登録したい場合は改めて issue にします。
