### ISSUE TITLE
Need to testing codes

### ISSUE THREAD

**Issue by spring-raining** [vivliostyle/vfm#25]
## Overview

Currently, VFM doesn't have any test codes but it's very important to do it for better code reliability. I'm guessing that language specification such likes VFM causes regression problems very easily.

**Comment by uetchy** [comment]
Actually, there are test codes available:
https://github.com/vivliostyle/vfm/blob/master/packages/vfm/src/index.test.ts

Some of the syntaxes lacks test case though, keeping coverage high would be nice.
