### ISSUE TITLE
spec: Image size

### ISSUE THREAD

**Issue by akabekobeko** [vivliostyle/vfm#26]
## Goals

Allow `widht` and `height` attributes of `<img>` to be specified as Markdown.

- May want to specify the size on demand for each image that appears in the sentence, such as novel illustrations
- By explicitly specifying the size, it becomes a countermeasure against the layout shift problem in the image table on the web browser

There is also a way to deal with #9 instead of `<img>`. In that case it would be `![](sample.jpg){width=100px height=100px}`.

**Markdown:**

1. width/height

```markdown
![alt](sample.jpg "title" width="100px" height="100px")
```
- Specify attributes individually
- Uses quotes to support CSS definable sizes

2. size

```markdown
![alt](sample.jpg "title" size="100px","100px")
```

- `width`/`height` specified by one
- In order of `width,height`
- Uses quotes to support CSS definable sizes
- If it is a single specification, use `width`
- Parse may be tedious due to nested structure

**HTML**

```html
<img src="sample.jpg" alt="alt" title="title" width="100px" height="100px">
```

## Prior Art

[GitHub Flavored Markdown Spec](https://github.github.com/gfm/) (6.7 Images) is not supported. There may be other Markdown dialects.

## Discussion

Refer to the following for web browser related support regarding layout shift (problem).

- [Compute img/video aspect ratio from width and height HTML attributes - Chrome Platform Status](https://chromestatus.com/feature/5695266130755584)
- [Mapping the width and height attributes of media container elements to their aspect-ratio - Web メディア技術 | MDN](https://developer.mozilla.org/ja/docs/Web/Media/images/aspect_ratio_mapping)
- [Release Notes - Safari Technology Preview - Safari - Apple Developer](https://developer.apple.com/safari/technology-preview/release-notes/#r99)
  - > Added support for using valid non-zero `width` and `height` attributes to become the default aspect ratio of `<img>`

**Comment by akabekobeko** [comment]
Additional:

- Units for CSS size may not need to be double escaped with quotes as there are no spaces or commas
  - `![alt](sample.jpg "title" width="100px" height="100px")` to `![alt](sample.jpg "title" width=100px height=100px)`
  - `![alt](sample.jpg "title" size="100px","100px")` to `![alt](sample.jpg "title" size=100px,100px)`
- Title notation follows GFM
  - It is better to give attributes and property names so that you can recognize that they are not in GFM
- It is arguable whether `width`/`height` or `size` is better
  - It is preferable to use either one because it will not cause confusion.
- It is also effective to use #9 without using this notation
  - This is also one of the purposes to discuss additional policy of attribute value.

**Comment by spring-raining** [comment]
I have two concerns about this suggestion.

- Setting `width` or `height` attribute is not the only way to define the size of the figures. CSS also defines apparent size of images ([like this](https://github.com/spring-raining/tbf07-draft/blob/0815969626a1bf56479b0d15af991ee6c1ea0cb2/scss/app.scss#L100-L108)), then obviously it can achieve the separation of semantics and styles.
- `size` argument may occur confusion with img's [`sizes`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-sizes) attribute.

However, a versatile feature that setting HTML attributes seems to be convenient! I'd like to discuss further proper specification.

**Comment by uetchy** [comment]
With #9, you can assign arbitrary attributes.

**vfm**
```markdown
![](image.png){width=100px height=100px}
```
**html**
```html
<img src="image.png" width="100px" height="100px">
```

**Comment by akabekobeko** [comment]
Shall we take a vote?

1. Add image formats like this suggestion
2. Support with custom attribute with #9

1 = 👍
2 = 👎

While making my own proposal, I've felt enough with #9.

**Comment by akabekobeko** [comment]
I think #9 is enough for the members who are currently participating in the discussion, including myself. Perhaps more votes will be added in the future, too.

This issue is dismissed as we have provided a way to specify the size of the `<img>` on demand and have confirmed the custom attribute policy.

In the future, if you have any requests or suggestions regarding attributes, I thought it would be good to present this issue with #9.
