### ISSUE TITLE
Processor-independent math output

### ISSUE THREAD

**Issue by spring-raining** [vivliostyle/vfm#30]
Current VFM library outputs inline/block math notation as preprocessed by rehype-katex. For example, `$\\Sigma$` yields

```html
<span class="math math-inline"><span class="katex"><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.68333em;vertical-align:0em;"></span><span class="mord">Σ</span></span></span></span></span>
```

However, this output forces us to load the KaTeX library and cannot keep forward compatibility even if KaTeX release changes preprocess results in the future.

In the example of Vivilostyle, it supports runtime typesetting using MathJax by setting `data-math-typeset`. This HTML syntax is processor-independent so Vivlostyle can support another math typesetting processor if we're in necessary. I suppose it's a more preferable output result.

```html
<span data-math-typeset="true">$\\sigma$</span>
```

**Comment by akabekobeko** [comment]
@spring-raining 
VFM として `data-math-typeset` 的な対応をする場合、

- オプションに `data-math-typeset` 相当を追加
- `data-math-typeset: true` なら `$ ... $` を KaTex 化せず Vivliostyle のようにそのまま `<span data-math-typeset="true">` で囲む

でよいでしょうか？

**Comment by MurakamiShinyu** [comment]
TeX数式をMarkdownに埋め込む記法として [remark-math](https://github.com/remarkjs/remark-math/blob/main/packages/remark-math/readme.md#use) のものを使うようですが、MathJax での記法とは違いがあるので、

> そのまま `<span data-math-typeset="true">` で囲む

では不十分で、次のようにする必要があると思います:
- インライン数式は `$`…`$` や  `$$`…`$$` で囲まれているのを `\(` … `\)` に直して `<span data-math-typeset="true">`…`</span>` で囲む。
- ディスプレイ数式は `$$`…`$$` を `<div data-math-typeset="true">`…`</div>` で囲む。

**Comment by MurakamiShinyu** [comment]
VFMで生成するHTMLをVivliostyle.jsを使わないで閲覧する場合にMathJaxを有効にするには、HTMLに次のようなscriptタグが必要です。

```html
<script async src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js?config=TeX-MML-AM_CHTML"></script>
```

Vivliostyle.jsは、文書ソースHTMLにあるscriptは無視したうえで、常にMathJaxをロードするようになってます:
https://github.com/vivliostyle/vivliostyle.js/blob/master/packages/viewer/src/html/vivliostyle-viewer.ejs#L15

**Comment by akabekobeko** [comment]
@spring-raining 
#37 の議論を踏まえて #89 で対応しました。VFM 1.0 としては数式を明示的に有効とした場合に限定し、村上さんのコメントされている MathJax の書式と `<script>` タグの出力を実施します。VFM 1.0-alpha.19 に反映されていますので、この対応でよろしければ本件を close してください。

議論の継続が必要ならばその旨、コメントをお願いします。

**Comment by MurakamiShinyu** [comment]
@akabekobeko @spring-raining (https://github.com/vivliostyle/vivliostyle-cli/pull/182#issuecomment-829985914 に関連して)

mathをデフォルトで有効にするほうがよいのでないかと思いはじめています。

mathをデフォルトで無効にしたのは `$`...`$` が意図せず数式として扱われてしまう問題があるだろうということでしたが、pandoc と同様の `$`...`$` を数式扱いする条件が実装されたので、その問題はだいぶ解消しています。

ただし数式が使われていないHTMLでもMathJaxがロードされたり、その処理がされるのは効率的ではないので、実際にMarkdownに `$`...`$` または `$$`...`$$` の数式が出現した場合にかぎり 
`<script async src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js?config=TeX-MML-AM_CHTML"></script>`
と `data-math-typeset="true"` を出力するのがよいと思います。

**Comment by akabekobeko** [comment]
`math` をデフォルトで有効にすることと vivliostyle-cli で math が有効にならないことは別問題ではないでしょうか？

vivliostyle-cli の実装として VFM の `math` オプションをどのように扱っているかを明確にするのが先の話だと思います。もし `VFM` または `stringify` 関数に `math` オプションを指定しているのに無視されているとしたら VFM のバグですので直す必要があります。指定していないとしたらこれらの関数に `math` オプションを追加した意味が薄れます。これは外部からの指定に備えたもので、主に vivliostyle-cli を想定しています。

とりあえず VFM として `math` のデフォルト有効化と実処理がなされた場合のみ hast を実行する案は検討しますが、↑についても並行して対応をお願いします。

**Comment by akabekobeko** [comment]
ざっと調べたメモ。

- `math` のデフォルト有効は容易、オプションの扱いを変更するだけでよい
- `math` が処理された場合のみ hast 実行は難しそう
  - remark-parse 対応した場合の mdast は `Plugin` 型としているが、これの引数に `VFile` を取れないようだ
  - mdast から hast に情報伝達する手段として `VFile` を利用できない
  - hast の前にある handler は `VFile` を取れないようだ
  - グローバル変数が必要になるかも知れない

インターフェース変更して `VFile` を受け渡せるか、それともグローバル変数などの代替手段にするかを継続調査 & 検討する。

**Comment by akabekobeko** [comment]
この Issue の話題とは別の話になるので #93 を用意しました。あちらで検討します。

**Comment by MurakamiShinyu** [comment]
> math をデフォルトで有効にすることと vivliostyle-cli で math が有効にならないことは別問題ではないでしょうか？

はい、別問題なのですが、関係しています。

- vfm で math がオプションになったのに、vivliostyle-cli でそのオプションを指定することができない 

という vivliostyle-cli 側の問題と、

- vfm で math オプションのデフォルトを false としたのは適切だったか？　true とするべきではないか

という問題です。

vfm で math オプションのデフォルトを true にするのであれば、vivliostyle-cli 側は現状のままでも、数式を使うことができます。vivliostyle-cli から vfm の数式を無効にすることはできませんが、vivliostyle-cli の以前のバージョン（＋vfm の以前のバージョン）でも katex による数式を常に有効にしていたので、数式を無効にすることができないことで困るユーザーは多くはないでしょう。数式エンジンが katex から MathJax に変わるというだけで、エッジケースを除けば以前と同じ結果が得られるはずです。

 vfm のオプションを vivliostyle-cli から指定することについては、別に検討して vivliostyle-cli の次回以降のリリースに反映させるのでよいと思います。

**Comment by akabekobeko** [comment]
承知しました。村上さん要望については #94  で対応してみました。

**Comment by akabekobeko** [comment]
@spring-raining @MurakamiShinyu 
Issue 登録時と数式に関する仕様が色々と変わりましたが MathJax サポートにあわせてそれを囲む `<span>` へ `data-math-typeset="true"` を出力するようにしました。

VFM 1.0.0-alpha.21 にて反映されるのでご確認ください。この対応でよろしければ Issue を close してください。

**Comment by spring-raining** [comment]
@vivliosytle/vfm@v1.0.0-alpha.21 で `<span class="math inline" data-math-typeset="true">` として出力されることを確認しました！ ご対応ありがとうございます。
