### ISSUE TITLE
Behavior of break lines inside inlineMath is strange

### ISSUE THREAD

**Issue by spring-raining** [vivliostyle/vfm#31]
## Step to reproduce

1. Convert the latter VFM document.

```md
$x
y$
```

## Actual output

```html
<p><span class="math math-inline"><span class="katex"><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.625em;vertical-align:-0.19444em;"></span><span class="mord mathdefault">x</span><span class="mord mathdefault" style="margin-right:0.03588em;">y</span></span></span></span></span></p>
```

I'm not sure this is a bug but other inline syntax rules cancel consuming when a new line appears. This behavior might confuse VFM users.

## Expected behavior

```html
<p>$x<br>
y$</p>
```

**Comment by akabekobeko** [comment]
これは恐らく #50 関連だと思われるので再現確認してみます。

**Comment by akabekobeko** [comment]
@spring-raining 
VFM 1.0 としては MathJax をサポートすることになり、実装を変更しました。その際に `math.test.ts` で `inline: multiline` のテストへ本 Issue のような複数行にまたがる数式を定義して

```markdwon
$x = y
1 + 1 = 2$
```

その結果が改行で分離されずに

```html
<p><span class="math inline" data-math-typeset="true">\\(x = y
1 + 1 = 2\\)</span></p>
```

となることを確認しています。これは現時点の最新版である VFM 1.0.0-alpha.21 で反映されています。この対応でよろしければ Issue を close してください。問題があればその旨、ご指摘ください。

**Comment by spring-raining** [comment]
@vivliosytle/vfm@v1.0.0-alpha.21 で `<span class="math inline" data-math-typeset="true">` として出力されることを確認しました！ ご対応ありがとうございます。
