### ISSUE TITLE
Cannot use escape syntax inside ruby context

### ISSUE THREAD

**Issue by spring-raining** [vivliostyle/vfm#32]
## Step to reproduce

1. Convert the latter VFM document.

```md
{a\|b|c}
```

## Actual output

```html
<p><ruby>a\<rt>b|c</rt></ruby></p>
```

## Expected behavior

```html
<p><ruby>a|b<rt>c</rt></ruby></p>
```

**Comment by akabekobeko** [comment]
`|` のエスケープが効かない問題。調査します。

**Comment by akabekobeko** [comment]
本 issue の修正とレビュー結果を反映した [1.0.0-alpha.27](https://github.com/vivliostyle/vfm/releases/tag/v1.0.0-alpha.27) をリリースしたので close します。
