### ISSUE TITLE
spec: Footnotes

### ISSUE THREAD

**Issue by MurakamiShinyu** [vivliostyle/vfm#33]
## Goals

https://www.w3.org/TR/css-gcpm-3/#creating-footnotes has footnote examples with the following HTML markup:
```html
<p>Paragraph text<span class="footnote">Footnote text</span></p>
```

To get this HTML, the following markdown syntax will be useful:

```
Paragraph text[^ Footnote text]
```

## Prior Art

[Vivliostyleで本を作ろう](https://github.com/spring-raining/tbf08-draft) uses this footnote markdown syntax.

## Discussion

There are other markdown footnote syntax proposals:
https://www.markdownguide.org/extended-syntax/#footnotes

**Comment by MurakamiShinyu** [comment]
Adopting [remark-footnotes](https://github.com/remarkjs/remark-footnotes) will be fine.

> ```
> Here is a footnote reference,[^1]
> another,[^longnote],
> and optionally there are inline
> notes.^[you can type them inline, which may be easier, since you don’t
> have to pick an identifier and move down to type the note.]
> 
> [^1]: Here is the footnote.
> 
> [^longnote]: Here’s one with multiple blocks.
> 
>     Subsequent paragraphs are indented to show that they
> belong to the previous footnote.
> 
>         { some.code }
> 
>     The whole paragraph can be indented, or just the first
>     line.  In this way, multi-paragraph footnotes work like
>     multi-paragraph list items.
> 
> This paragraph won’t be part of the note, because it
> isn’t indented.
> ```

## Inline footntes

The (optional) inline footntes syntax of remark-footnotes  differs the one we used in [Vivliostyleで本を作ろう](https://github.com/spring-raining/tbf08-draft). That was `[^ footnote text]` and not `^[footnote text]`.

**Comment by akabekobeko** [comment]
[remark/plugins.md](https://github.com/remarkjs/remark/blob/main/doc/plugins.md) によれば remark 13 対応済み。[History for package.json](https://github.com/remarkjs/remark-footnotes/commits/main/package.json) を読むと VFM v1.0 で利用するなら v2.0.0、remark 13 対応の VFM 2.0 以降なら最新を採用すればよいらしい。

現状と将来の両対応できそうなので VFM v1.0 実装を検討します。

**Comment by akabekobeko** [comment]
@MurakamiShinyu 
PR #96 として対応しました。機能として組み込み済みだったので対応は npm 更新と不足していたドキュメント、テスト コード追加となります。PR 側のレビューが通ったら 1.0.0-alpha.22 に反映してリリース予定です。

**Comment by MurakamiShinyu** [comment]
> Adopting [remark-footnotes](https://github.com/remarkjs/remark-footnotes) will be fine.

と書いたのですが、この実装では以下の問題があることに気がつきました。

- footnote ではなく endnote であること
    - Vivliostyle での https://www.w3.org/TR/css-gcpm-3/#creating-footnotes のサポートが活かされない
- 注参照の番号と注番号とが一致しないこと
    - これは remark-footnotes で生成される HTML の問題。pandoc なら注参照の番号が注番号と一致するように付け直される。（した図、左は remark-footnotes での結果、右は pandoc での結果）

![Screen Shot 2021-05-10 at 2 52 48](https://user-images.githubusercontent.com/3324737/117581993-e0a41000-b13a-11eb-8745-7b360491c1e8.png)

**Comment by akabekobeko** [comment]
> footnote ではなく endnote であること

すみません、これらの違いがわかりません。

- 脚注を `<span>` で囲み CSS により `bottom` へ配置する = footnote
- 脚注をリンク変換して対象テキストは `<div>` で末尾に配置する = endnote

ということでしょうか？

> 注参照の番号と注番号とが一致しないこと

remark-footnotes は通常の脚注を連番 `fn-N`、インラインならそのまま `fn-name` とするようです。インラインのサポートをやめて (オプションで指定可能) 連番のみにするか、後工程で HTML を加工すれば対応可能と思われます。

以上を踏まえて相談です。

remark-footnotes は remark 公式プラグインで remark 13 前後どちらも対応されていること、既に VFM として組み込み済みであることから VFM 1.0 対応としました。

しかし連番については remark-footnotes として対応可能なものの、endnote と footnote の違いが私の認識どおりであれば HTML としての構造が大きくことなるため、スクラッチで実装が必要となります。またそれは remartk 13 以降も想定しなければなりません。

よって 2.0 に見送る (remark-footnotes も外す) か、1.0 で対応が必要なら厳密な仕様の再定義をお願いします。

**Comment by MurakamiShinyu** [comment]
Create Bookのドキュメント (by @ogwata) に「注」がすでに書かれているので、外してしまうと困ると思います：
https://docs.vivliostyle.org/#/ja/create-book#%E6%B3%A8

v1.0 では次のように制限したfootnote/endnoteサポートでどうでしょうか？

- Inline footnote の構文 `^[ ... ]` は `<span class="footnote"> ... </span>` に変換する。（remark-footnotes の inline footnote 機能は使わない）
- それ以外の footnote 構文 `[^xx]` ... `[^xx]: ...` は remark-footnotes を使う。注参照の番号は注番号と一致するように加工する。

**Comment by MurakamiShinyu** [comment]
> remark-footnotes のインライン構文が無効なら連番のみとなるので HTML 加工は不要ではないでしょうか？

いいえ。次の例：

```md
Here is a footnote reference[^1].

Here is another footnote reference[^A].

Here is more footnote reference[^2].


[^1]: Here is a footnote.

[^A]: Here is another footnote.

[^2]: Here is more footnote.
```

現状は次のようにHTMLに変換されます:

```html
<p>Here is a footnote reference<sup id="fnref-1"><a href="#fn-1" class="footnote-ref">1</a></sup>.</p>
<p>Here is another footnote reference<sup id="fnref-a"><a href="#fn-a" class="footnote-ref">A</a></sup>.</p>
<p>Here is more footnote reference<sup id="fnref-2"><a href="#fn-2" class="footnote-ref">2</a></sup>.</p>
<div class="footnotes">
  <hr>
  <ol>
    <li id="fn-1">Here is a footnote.<a href="#fnref-1" class="footnote-backref">↩</a></li>
    <li id="fn-a">Here is another footnote.<a href="#fnref-a" class="footnote-backref">↩</a></li>
    <li id="fn-2">Here is more footnote.<a href="#fnref-2" class="footnote-backref">↩</a></li>
  </ol>
</div>
```

HTMLの表示結果は:

<blockquote>
<p>Here is a footnote reference<sup id="fnref-1"><a href="#fn-1" class="footnote-ref">1</a></sup>.</p>
<p>Here is another footnote reference<sup id="fnref-a"><a href="#fn-a" class="footnote-ref">A</a></sup>.</p>
<p>Here is more footnote reference<sup id="fnref-2"><a href="#fn-2" class="footnote-ref">2</a></sup>.</p>
<div class="footnotes">
<hr>
<ol>
<li id="fn-1">Here is a footnote.<a href="#fnref-1" class="footnote-backref">↩</a></li>
<li id="fn-a">Here is another footnote.<a href="#fnref-a" class="footnote-backref">↩</a></li>
<li id="fn-2">Here is more footnote.<a href="#fnref-2" class="footnote-backref">↩</a></li>
</ol>
</div>
</blockquote>

このように 注参照番号 (1, A, 2) と注番号 (1, 2, 3) が不一致です。

pandoc でHTMLに変換した結果は次のようになります:

```html
<p>Here is a footnote reference<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>.</p>
<p>Here is another footnote reference<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>.</p>
<p>Here is more footnote reference<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>.</p>
<section class="footnotes" role="doc-endnotes">
<hr />
<ol>
<li id="fn1" role="doc-endnote"><p>Here is a footnote.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2" role="doc-endnote"><p>Here is another footnote.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3" role="doc-endnote"><p>Here is more footnote.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>
```

このHTMLの表示結果は:

<blockquote>
<p>Here is a footnote reference<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>.</p>
<p>Here is another footnote reference<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>.</p>
<p>Here is more footnote reference<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>.</p>
<section class="footnotes" role="doc-endnotes">
<hr />
<ol>
<li id="fn1" role="doc-endnote"><p>Here is a footnote.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2" role="doc-endnote"><p>Here is another footnote.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3" role="doc-endnote"><p>Here is more footnote.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>
</blockquote>

**Comment by akabekobeko** [comment]
条件としては

- 数値のみで指定された場合はそれを昇順
- 数値以外で指定された場合は数値よりも後 (末尾) に定義順で昇順

でよいでしょうか？remark-footnotes として連番処理してると思っていたのですが、出力結果から察するに番号は考慮しておらず名前からそのまま `id` 生成しているだけのようですね。

そうなると 2、7、A、5 のような順で定義された場合に並べ替えるのか？という課題もあります。ユーザーが `1...N` で指定せず、登場順もバラバラのケースですね。数値を評価するなら `2, 5, 7, A` にする必要があります。ただし順番としては昇順になりますが番号は `<ol><li>` と一致しません。

**Comment by akabekobeko** [comment]
推測ですが remark-footnotes としてはこうしたケースまで考慮して対応するのが難しいためユーザーの自己責任でそのまま `[^...]` に指定されたものを対応付けて `id` 化しているのではないでしょうか。どこまで考慮するか、という話になります。

**Comment by MurakamiShinyu** [comment]
もとの `[^xx]` の xx の値に関係なく、出現順に連番にすればよいのでないでしょうか。pandocではそうなってると思います。

[remark-footnotes](https://github.com/remarkjs/remark-footnotes) には、
> plugin to add support for pandoc footnotes

ということなのに、pandocの動作と合っていません。remark-footnotes のほうにバグ報告するとよいかもしれませんね。

著書は番号を連番になっているかどうかを気にしないで適当につけることができて（数値でも英字でもなんでもよい）、それが自動的に連番になるということに意味があります。（あとから最初の方に注を追加したとき番号を著者が自分で付け直す必要がないように）

**Comment by akabekobeko** [comment]
pandoc 側のリンクを見ると `A` のものもリンク自体を連番にしていますね。これも実現できそうなので対応します。よって

> リンク処理と `<ol><li>` の順番は remark-footnotes そのまま、`id` は連番にならないが一意であればよく表示上の文中リンク連番と `<ol><li>` は整合が取れるためよしとする

は

- リンク元を連番処理する際、対応する `<ol><li>` 側の `id` も連番にする

としておきます。

**Comment by MurakamiShinyu** [comment]
remark-footnotes の issues を見たら
"Footnote Links should not simply replicate reference tag"
https://github.com/remarkjs/remark-footnotes/issues/3
というissueがあり、その中で、番号の付け直しも行う 
https://github.com/jackfletch/remark-numbered-footnote-labels
が紹介されていました。参考になるかもしれません。

**Comment by MurakamiShinyu** [comment]
remark-footnotesとpandocでの生成されるHTMLコードを比較すると次の違いがあります:

| remark-footnotes | pandoc |
|-------|---------|
| `<sup id="fnref-1"><a href="#fn-1" class="footnote-ref">1</a></sup>` | `<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>` |
| `<div class="footnotes">` | `<section class="footnotes" role="doc-endnotes">` |
| `<a href="#fnref-1" class="footnote-backref">↩</a>` | `<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a>` |

要点をまとめると
- pandoc のほうは https://www.w3.org/TR/dpub-aria-1.0/#roles の role 属性が付加されている
- 注参照の a 要素：remark-footnotes では親要素が sup 要素、pandoc では子要素が sup 要素
- 注をまとめたブロックは remark-footnotes は div 要素、pandoc は section 要素
- 逆参照リンクのクラス名が remark-footnotes は "footnote-backref"、pandoc は "footnote-back"

このうち、role属性はpandocと同様に出力するのがよいと思います。
`^[...]` を `<span class="footnote">...</span>` にする場合も、`<span class="footnote" role="doc-footnote">...</span>` と出力するのがよさそう。

注参照の sup 要素については、pandocのほう（子要素が sup 要素）がより好ましいです。（注参照番号のスタイルを指定する場合など、そのほうが都合がよい）

div 要素か section 要素かと、逆参照リンクのクラス名は、どちらでも問題ないですが、可能なら pandoc 互換とするのがよさそう。

**Comment by akabekobeko** [comment]
まずはインラインだけ対応できないか調べたら remark-footnotes のものを OFF にすると `^[...]` の `[...]` がリンクとして処理されて `linkReference` になってしまう。そのため remark プラグインとして CommonMark/GFM 構文と排他しないと対応不能。

**Comment by akabekobeko** [comment]
## remark-footnotes を継続する場合 

- インライン構文は独自実装が必要だが、前述のように remark プラグイン化が必要
- HAST の加工が多い
  - 対応は可能だがインライン構文が別体になることを考慮すると対応してあまりに場当たり 

## remark-footnotes をやめる場合

- remark プラグインと競合する構文を排他する必要あり
  - remark プラグインになる
  - remark 13 前後の移行対応が発生する、VFM 1.0 としての見送り条件 
- remark-footnotes 実装を見ると非常に多くの条件を想定していて、VFM として実装すると想定漏れで事故りそう
- インライン構文は可能かもしれないが、通常構文は 1 Node で完結しないため MDAST の横断的な処理も必要

## 折衷案

- remark-footnotes のソース コードを移植して MDAST 生成部分だけを直す
  - VFM 1.0 は remark-footnotes v2.0.0、VFM 2.0 では v3.0.0 以降の最新を移植する
  - remark-footnotes のライセンスは MIT なので VFM にも組み込み可能
  - ソース コードにライセンスが記述されていないが TSDoc 形式でオリジナルとその改変について明記する
  - そもそも Pandoc に言及しながら互換ではないので、それを直すことになる
- インライン構文もこの方法で対応する
  - 処理の複雑さ次第だが、remark-footnotes のように横断的に通常構文と混ぜてリスト生成するのを止める
  - インラインとしてそのまま出力する案でゆく
  - これはやってみないと良し悪しを判断できないので継続検討  

というわけで折衷案を #96 で試してゆく。

**Comment by akabekobeko** [comment]
もう一つの案。

- remark-footnotes をインラインも含めてそのまま採用
- インラインも通常構文と同じくリンクと `<ol><li>` のままにする = 元の文に埋め込む方式としない
- https://github.com/vivliostyle/vfm/issues/33#issuecomment-837741240 の Pandoc 例のとおり HAST で HTML 加工する

この方法のよいところは remark-footnotes をブラックボックスにしたままでいられる点。インライン構文と CommonMark/GFM 排他 (remark 13 前後の対応必須) もしなくて済む。インラインで特別な対応を要望されていたため自作 or 移植改訂を検討していたが、たとえ HAST 処理が増えてもこちらの方がリスクは少ないはず。

**Comment by akabekobeko** [comment]
> `<span class="footnote"…>` をサポートするのは VFM 2.0 からでもよいと思います。
>  VFM 2.0 から、デフォルトでは 1.0 と同じ（インラインも通常構文と同じくリンク）として、オプションでインライン構文を `<span class="footnote"…>` にするのでどうでしょう。

Pandoc でインライン構文 `^[...]` を試したら remark-footnotes と同様に `<ol><li>` 側へ追加されました。Pandoc を手本とするならここもそのままにするほうがよいと思います。つまり remark-footnotes の処理はそのまま利用して HTML タグや階層 (`<a>` と `<sup>` を逆転させる、など) だけの変更に留めたいです。

remark-numbered-footnote-labels については開発者の方が多忙なようで開発が止まっており

- [remark@next (13) · Issue #4 · jackfletch/remark-numbered-footnote-labels](https://github.com/jackfletch/remark-numbered-footnote-labels/issues/4)

この Issue もしばらく議論がありません。実装を見るに remark の `Parser` 依存はないため remark 13 前後どちらでも動作しそうですが、継続的なメンテナンスに不安があります。

一方 remark-footnotes は remark 公式なので最新版は micromark 化されており継続開発に期待できそうです。Pandco と異なる部分についても Issue で対応してもらえるかもしれません。

以上を踏まえ

- remark-footnotes を継続採用する
- remark-footnotes のインラインは有効にする
  - リンク元と先を異なる Node に分割するという挙動は Pandoc と共通している
- HAST で HTML を加工する
  - Pandoc との齟齬を解決する
  - `class` や `id` から対象要素の特定は可能

とします。

**Comment by akabekobeko** [comment]
Markdown

```markdown
Here is a footnote reference,[^1]
another,[^longnote],
and optionally there are inline
notes.^[you can type them inline, which may be easier, since you don’t
have to pick an identifier and move down to type the note.]

[^1]: Here is the footnote.
[^longnote]: Here’s one with multiple blocks.

    Subsequent paragraphs are indented to show that they
    belong to the previous footnote.

        { some.code }

    The whole paragraph can be indented, or just the first
    line. In this way, multi-paragraph footnotes work like
    multi-paragraph list items.

This paragraph won’t be part of the note, because it
isn’t indented.
```

to HTML `pandoc -f markdown -t html ./sample.md > ./sample.html`

```html
<p>Here is a footnote reference,<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> another,<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>, and optionally there are inline notes.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p>
<p>This paragraph won’t be part of the note, because it isn’t indented.</p>
<section class="footnotes" role="doc-endnotes">
<hr />
<ol>
<li id="fn1" role="doc-endnote"><p>Here is the footnote.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2" role="doc-endnote"><p>Here’s one with multiple blocks.</p>
<p>Subsequent paragraphs are indented to show that they belong to the previous footnote.</p>
<pre><code>{ some.code }</code></pre>
<p>The whole paragraph can be indented, or just the first line. In this way, multi-paragraph footnotes work like multi-paragraph list items.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3" role="doc-endnote"><p>you can type them inline, which may be easier, since you don’t have to pick an identifier and move down to type the note.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>
```

村上さんの提案にあるとおり、VFM でもこの HTML のような構成にする予定です。

**Comment by akabekobeko** [comment]
`id` も `fn-XXXX` ではなく `fnN` にしようと思います。リンク元を連番化する際の処理で元と先を一緒に処理するのがよさそうですね。

**Comment by akabekobeko** [comment]
#96 で対応し VFM 1.0.0-alpha.22 としてリリースしたので close。
