### ISSUE TITLE
Language default should be undefined, not 'en'

### ISSUE THREAD

**Issue by MurakamiShinyu** [vivliostyle/vfm#34]
https://github.com/vivliostyle/vfm/blob/master/README.md#language-default-en
> `language` (default: `en`)

Why not leave the language default undefined?

Wrong language information causes problem, so when the language is unknown the output HTML start tag should be `<html>` rather than `<html lang='en'>`. 

BTW, is it possible to specify the document language in VFM code?

Pandoc's Markdown can specify the lang attribute in YAML metadata block. https://pandoc.org/MANUAL.html#language-variables

[pandocのMarkdownで言語を指定するテスト](https://pandoc.org/try/?text=---%0Atitle%3A+%E3%83%86%E3%82%B9%E3%83%88%0Alang%3A+ja%0A---%0A%0A%E3%81%82%E3%80%82%0A%0A&from=markdown&to=html5&standalone=1)

**Comment by akabekobeko** [comment]
まず標準の `lang` ですが `src/index.ts` を読むに `VFM`または `stringify`  関数に `language` オプションを指定しない場合は `en` になります。ここに指定された値が [rehype-document](https://github.com/rehypejs/rehype-document) へ渡されて `lang` 属性として設定されます。以下は実際に動かしてみたテスト コードです。

```ts
import assert from 'assert';
import { stringify } from '../../src/index';

it('language', () => {
  const actual = stringify('text', { language: 'ja' });
  const expected = `<!doctype html>
<html lang="ja">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<p>text</p>
</body>
</html>
`;
  assert.strictEqual(actual, expected);
});
```

しかし VFM としてこの値の既定値をやめても rehype-document の既定値も `en` となるため、これを通す限り `lang` は常に設定されます。調査内容を要約します。

- `lang` 属性は v1.0.0-alpha.14 時点の `VFM` と `stringify` で指定可能
- 指定された言語は rehype-document で設定される
  - rehype-document としては [BCP 47](https://tools.ietf.org/html/bcp47) の値を期待しているが、デタラメな言語名でもそのまま素通しする
  - キャンセルできるかと `"undefined"`、`"none"`、`"test"` のような文字列を試したが、そのまま設定される
  - `undefined` なら既定値の `"en"` が指定される
  - `null` は TypeScript の型定義としてエラー

つまり「言語指定は可能だが未指定は不可」となります。

**Comment by akabekobeko** [comment]
VFM として `en` を既定値としていますが rehype-document  任せにしてあちらも同様の既定値なので、これは指定しなくてよいかもしれませんね。

**Comment by akabekobeko** [comment]
既定値を未指定にするとしたら

1. rehype-document に要望を出す
2. rehype-document をやめて独自に処理する

でしょうか。

**Comment by MurakamiShinyu** [comment]
空文字列 "" は指定できませんか?　lang="" が出力されるなら問題ないはず

**Comment by akabekobeko** [comment]
すみません、書き忘れてました。`""` は `en` になります。[rehype-document/index.js](https://github.com/rehypejs/rehype-document/blob/main/index.js) を読むと

```js
{lang: settings.language || 'en'}
```

のように判定しているので空文字は `false` となり `en` ですね。

**Comment by MurakamiShinyu** [comment]
多言語対応の組版システムであるVivliostyleとしては、間違ったlang属性がある文書が作られることはできるだけなくしたいです。

ブラウザによりlang属性の組版結果への影響は少し違いますが、特にFirefoxでは、langが日本語か中国語でないと、漢字やカナの文字間を調整する行揃え(text-align: justify)が機能しません。ユーザーのマシン環境が日本語の設定であれば、lang指定がない場合でも日本語として扱われて行揃えがされますが、lang指定があるとだめです。（ChromeとSafariはこの問題はないです。）
いまテスト([JSBin](https://jsbin.com/huboraguci/edit?html,css,output))したのですが、`lang=""` でもだめでした。デフォルトは lang 属性を出力しないのが望ましいです。

> - キャンセルできるかと "undefined"、"none"、"test" のような文字列を試したが、そのまま設定される

それを利用して、たとえば `language = "none"` を  rehype-document に渡して、出力された HTML の `lang="none"` を後処理で除去するというような処理はどうでしょう？

**Comment by akabekobeko** [comment]
提案ありがとうございます。最終的に単なる文字列となるため正規表現で置換してしまうのも確かに手ですね。他の方法として以下を考えてみました。

1.  rehype-document  を VFM へ移植する
2. 最終的な HAST で `lang` を後処理する

1 は rehype-document 実装が想像よりも小さいので移植するのはどうか？という案です。しかし `index.js` の履歴をみたら 16 日前に更新しており、運用コスト面で原作にのったほうが安全そうなのであまり好ましくないですね。

2 は村上さん案の対象である文字列の元になる HAST を明示的に処理します。実装としては

1. VFM 関数の `language` オプション既定値を `"en"` から `undefined` に変更
2. `language` オプションが `undefuned` なら `rehype-stringify` が処理される前に HAST の `lang` を消す

というのを想定しています。この案が難しければ村上さん案で対応してみます。

**Comment by akabekobeko** [comment]
メモ。

VFM のドキュメント的には README の API 欄にて規定値が `en` であることは記載されている。これは省略不能 (必須) であることを明示しているともいえるため、現時点の設計 (仕様) はあながち間違いともいえない。

ただし `lang` に指定する言語を正確に決めるのは難しいこと (国) もある。MDN で BCP 47 も踏まえて解説されているので読んでみると

- [lang - HTML: HyperText Markup Language | MDN](https://developer.mozilla.org/ja/docs/Web/HTML/Global_attributes/lang)

言語はよいとして書記体系や地域も必要となることがあるだろう。`lang` を指定せず `unknown` とすることで、この難しい指定を OS や Web ブラウザーに委ねられることはユーザーにとって需要があるかもしれない。

よって私としても既定値は `en` のように何らかの言語を指定するのではなく `lang` なしとする方針に賛成。

**Comment by akabekobeko** [comment]
HAST の加工で対応可能なので PR  & merge しました。次のリリースに反映されます。

**Comment by akabekobeko** [comment]
API (`language` オプション) の仕様変更につ README も書き換えたので実際の挙動とあわせるために本対応が反映された alpha.15 をリリースしました。
