### ISSUE TITLE
Math equation で数式が正しく表示されない

### ISSUE THREAD

**Issue by ogwata** [vivliostyle/vfm#36]
title: **Italics and topscripts are not parsed in Math equality**

1. markdownで以下のように記述（written in markdown as follows）　
```
$$f(x) = x^2$$
```
2. 出力されたPDFファイルのキャプチャは下記の通りです。（The capture of the output PDF file is as follows.）
<img width="65" alt="スクリーンショット 2020-08-08 2 09 07" src="https://user-images.githubusercontent.com/31482860/89671690-64b43780-d91e-11ea-83ea-01cc615bb607.png">

なお、パースされたHTMLは下記の通りです。（In addition, the parsed HTML is as follows.）
```
<p>
  <span class="math math-inline">
    <span class="katex">
      <span class="katex-html" aria-hidden="true">
        <span class="base">
          <span class="strut" style="height:1em;vertical-align:-0.25em;"></span>
          <span class="mord mathdefault" style="margin-right:0.10764em;">f</span>
          <span class="mopen">(</span>
          <span class="mord mathdefault">x</span>
          <span class="mclose">)</span>
          <span class="mspace" style="margin-right:0.2777777777777778em;"></span>
          <span class="mrel">=</span>
          <span class="mspace" style="margin-right:0.2777777777777778em;"></span>
        </span>
        <span class="base">
          <span class="strut" style="height:0.8141079999999999em;vertical-align:0em;"></span>
          <span class="mord">
            <span class="mord mathdefault">x</span>
            <span class="msupsub">
              <span class="vlist-t">
                <span class="vlist-r">
                  <span class="vlist" style="height:0.8141079999999999em;">
                    <span style="top:-3.063em;margin-right:0.05em;">
                      <span class="pstrut" style="height:2.7em;"></span>
                      <span class="sizing reset-size6 size3 mtight">
                        <span class="mord mtight">2</span>
                      </span>
                    </span>
                  </span>
                </span>
              </span>
            </span>
          </span>
        </span>
      </span>
    </span>
  </span>
</p>
```

**Comment by MurakamiShinyu** [comment]
[KaTeX](https://github.com/KaTeX/KaTeX) のスタイルシートとフォントがロードされていないため数式の表示にはなりません。

VFM→HTML変換にKaTeXによるHTMLへの変換を組み込むのであれば、https://github.com/KaTeX/KaTeX#starter-template にあるように HTML に次のようなスタイルシート指定が必要です。

```html
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.css" integrity="sha384-AfEj0r4/OFrOo5t7NnNe46zW/tFgW6x/bCJG8FqQCEo3+Aro6EYUG4+cU+KJWu/X" crossorigin="anonymous">
```

関連Issues:
KaTeXによるHTMLへの変換をVFMに組み込むことの是非は #30 で。
VFMとVivliostyle.jsでサポートする数式記法については #18 で。

**Comment by akabekobeko** [comment]
@ogwata @MurakamiShinyu 
VFM というより変換された HTML をその後、どう扱うかの問題のようですね。VFM として対応するものとしては @MurakamiShinyu さんコメントに挙げられている個別の issue となるでしょう。よって本件は close したいのですが、いかがでしょうか？

**Comment by akabekobeko** [comment]
@ogwata 
VFM 1.0.0-alpha.19 にて #37 で議論された数式を実装しました。ここでは Vivliostyle で MathJax を処理するための `<script>` 追加もおこないます。

この対応をもって本件の解決、または前述の私のコメントで書いたように VFM 外の対応が必要ならその旨をコメントのうえ issue を close してください。VFM として追加対応が必要ならば本 issue で議論を継続しましょう。

**Comment by akabekobeko** [comment]
@ogwata 
VFM 1.0.0-alpha.21 にて数式まわりの修正を実施しました。本件へ関係しそうなものとしては MathJax 処理対象のタグへ指定する属性を `<body>` から数式を包む `<span>` に変更しています。おそらくここまでの対応で本件は修正されていると思われますので再確認のうえ、正常動作したならば Issue を close してください。

問題がある場合はその旨をコメントお願いします。

**Comment by akabekobeko** [comment]
@ogwata 
本件について現時点の最新 VFM + Vivliostyle で確認をお願いします。前述のように村上さんの指摘している `<script>` タグを出力するようにしたので VFM が変換した HTML は Vivliostyle 経由で MathJax の数式を処理できるはずです。

**Comment by ogwata** [comment]
Markdownで`$$f(x) = x^2$$`と書いたものを、Vivliostyle CLIでビルドすると、下記のようにHTMLに変換されることを確認しました。

`<p><span class="math display" data-math-typeset="true">$$f(x) = x^2$$</span></p>`


ご対応いただき、ありがとうございました。本Issueはクローズします。
