### ISSUE TITLE
spec: 数式モード

### ISSUE THREAD

**Issue by yamasy1549** [vivliostyle/vfm#37]
## Goals
オプションで数式モードを使えるようにする。数式モードでは、`$` や `$$` を数式記法として使えるようになる。
数式モードの指定方法は、優先度の高い順に
- front matter ( `math: true` )
- vivliostyle.config.js
- CLIのオプション

など。

## Discussion
> $ は汎用的すぎて数式よりも用途が多く、それによる解析事故が起きそうなので。一方、数式が大量に登場する文章 (論文とか) を書くユーザーは MathJax で常用しているので使いたくなるだろう。
> なのでオプション指定してその文章が MathJax をサポートしているか否かを明示するのはどうか。
> https://github.com/vivliostyle/vfm/issues/18#issuecomment-670831119

**Comment by yamasy1549** [comment]
数式モードが true のときに、Katex を使うのか MathJax を使うのかもユーザーが指定できるようになりたい
ref: #30

**Comment by akabekobeko** [comment]
もし VFM で Katex、MathJax のように複数の解析をサポートするとしたら Frontmatter のプロパティーを真偽値ではなく文字列にして、エンジンを指定する方式にするのはどうでしょうか。

Katex なら

```yaml
math: 'katex'
```

で MathJax の場合は

```yaml
math: 'mathjax'
```

とします。`math` が未指定、もしくは未定義のエンジンなら数式は解析しません (これが既定値)。

**Comment by akabekobeko** [comment]
もしくは標準で常に Katex が有効で Frontmatter に明示的な `math: 'mathjax'` が指定された場合のみ、そのページの数式解析を変更するとか。

問題点としては数式解析の方法が複数となることですね。実装面ではメンテナンス対象が増えます。ユーザー的にはどちらを選択するのがよいか迷うかもしれません。また書籍の大半に数式が登場する場合、ページ単位の Frontmatter で個別指定するのは冗長かつ漏れが心配ですね。

これを避けるとしたら

1. 書籍全体の解析モードを config ファイルや CLI オプションで指定
2. ページ単位で切り替えたいなら Frontmatter で上書き

という感じでしょうか。

**Comment by akabekobeko** [comment]
@yamasy1549 
議論が途中で止まっています。私の提案も含めて希望される仕様がありましたらコメントをお願いします。とりあえず v1.0 検討としておきますが、影響範囲が大きそうなら v2.0 へ見送すことを検討します。

**Comment by yamasy1549** [comment]
@akabekobeko 
- `math` が未指定、もしくは未定義のエンジンなら数式は解析しない（デフォルト）
    - 数式を使わないユーザーが `$` の挙動で事故らないように
- 出版物全体の数式モードは CLI のオプションや vivliostyle.config.js ファイルで指定できる
- 原稿ごとに別々の指定をしたい場合は Frontmatter で指定できる

で、指定できる値は次の5つでしょうか。
- `asciimath`
- `mathml`
- `mathjax`
- `katex`
- `block`

**Comment by akabekobeko** [comment]
コメントありがとうございます。現在は常に `$...$` と `$$...$$` を拾って KaTex として処理している (remark-math) のですが、Frontmatter で未指定なら処理しないというのもありですね。ただし数式が頻出する文書 (論文など) で複数の Markdown ファイルがある場合、

- 都度 `math` を Frontmatter で指定するのは面倒
- Markdown ファイル毎に個別の記法を使い分けることがどれだけあるか？

という課題がありますね。執筆者が複数でも文書としては統一された記法を採用すると思われます。私が提案しておいてなんですが、大本の @yamasy1549 さんのとおり個別の Markdown としては `math: boolean` のみとし、記法は統一のほうがよさそうです。

そうなると記法の指定はオプションですかね。CLI なら `--math katex`、Node.js API なら `math: string` という感じで。

**Comment by yamasy1549** [comment]
> Markdown ファイル毎に個別の記法を使い分けることがどれだけあるか？

執筆者が複数だとそういうこともある……かもしれません（流派的に）。可能なら各MarkdownファイルのFrontmatterで記法の指定を上書きできるとうれしいですが、実装がむずかしければなくてもよいかもしれません。

**Comment by MurakamiShinyu** [comment]
> 数式を使わないユーザーが `$` の挙動で事故らないように

という理由で数式記法を有効にするのはオプションにするのでよいですが、その値について、

> で、指定できる値は次の5つでしょうか。
> 
> * `asciimath`
> * `mathml`
> * `mathjax`
> * `katex`
> * `block`

数式フォーマット(MathML, TeX数式, AsciiMath) と、それをMarkdownに埋め込む記法と、何を使って表示するか(MathJax, katex)とを分けて考えるとよいと思います。

### 数式フォーマットとMarkdownに埋め込む記法

- MathML の場合、HTMLコードと同様に Markdown の中に直接書けるはず。
- TeX数式を Markdown に入れる記法: `$`...`$` および `$$`...`$$` 
  ```
  Lift($L$) can be determined by Lift Coefficient ($C_L$) like the following
  equation.
  
  $$
  L = \frac{1}{2} \rho v^2 S C_L
  $$
  ```
  詳しくは: https://github.com/micromark/micromark-extension-math
- AsciiMath はどうやって Markdown に書く？

### MathJax vs katex

MathJaxでは３つの数式フォーマットとも扱える。Vivliostyle.jsでもともとサポート：FAQの [数式（MathML、TeX、AsciiMath）を埋め込むには？](https://vivliostyle.org/ja/faq/#%E6%95%B0%E5%BC%8Fmathmltexasciimath%E3%82%92%E5%9F%8B%E3%82%81%E8%BE%BC%E3%82%80%E3%81%AB%E3%81%AF)

katex のメリットは？

**Comment by akabekobeko** [comment]
remark-math は MDAST を担当するもので HAST として rehype-katex と rehype-mathjax を提供しているようですね。そして現在の VFM は `math.ts` を読むに rehype-katex のみを選択しています。

私は数式に詳しくないため KaTex と MathJax それぞれの特徴と選択可能にすることの意義について意見はないため @yamasy1549 さん @MurakamiShinyu (and more) で議論してただいたうえ、それに基づいて方針を決めたいです。

**Comment by akabekobeko** [comment]
それと #76 で実装途中だったことが判明したので Frontmatter とメタデータの HTML 反映へ対応しようとしています。数式の振る舞いについて、あちらも考慮して検討 (モード指定をどのようにするのがよいか？など) していただけるとありがたいです。

**Comment by yamasy1549** [comment]
@MurakamiShinyu 
> 数式フォーマット(MathML, TeX数式, AsciiMath) と、それをMarkdownに埋め込む記法と、何を使って表示するか(MathJax, katex)とを分けて考えるとよいと思います。

ありがとうございます、勘違いしてました。こういうことですかね？

| math: | デフォルト | `mathjax` | `katex` |
| --- | --- | --- | --- |
| TeX タイプ（`$` や`$$`） | 無効 | 有効 | 有効 |
| AsciiMath（<code>\`\`</code>） | 無効 | 有効 | 無効 |
| MathML（HTML コード） | 無効 | 有効 | 有効 |


> katex のメリットは？

MathJax と比べて速いようです。個人的にはどちらでもいいと思っています

**Comment by MurakamiShinyu** [comment]
katex は MathML 入力をサポートしていません。katex の issues にその要望がありましたが TeX 形式以外のサポートは当面無理ということで却下されてました:  https://github.com/KaTeX/KaTeX/issues/211

**Comment by MurakamiShinyu** [comment]
vfm 1.0 では MathJax のみサポートでどうでしょう？
オプション `--math`、config や frontmatter の `math: true` で有効とします。必要があれば将来 boolean 以外を指定できるようにするとよいでしょう。

`math: true` の場合の処理は以下:

- HTML 出力の head 要素内に `<script async src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js?config=TeX-MML-AM_CHTML"></script>` を出力
  - 注：MathJaxの最新は v3.1 だが v2 と v3 とのあいだで作り直されていて仕様が変わっている。参照: [MathJax docs: Upgrading from v2 to v3](http://docs.mathjax.org/en/latest/upgrading/v2.html)。VivliostyleではMathJax v3は未検証。そこでv2の最新版 "2.7.9" としている。
  - Vivliostyle Viewer はこの script タグの有無に関係なく常に [MathJax をロード](https://github.com/vivliostyle/vivliostyle.js/blob/master/packages/viewer/src/html/vivliostyle-viewer.ejs#L15)。この script タグは、Vivliostyle Viewer を通してではなく、普通の Web ページとしてこの HTML を閲覧するときのために必要。
- body 要素に属性 `data-math-typeset="true"` を出力
- インライン数式: `$`...`$` で囲まれた内容をそのまま（記号類がそのまま出力されること） `\(`...`\)` で囲んで出力
- ディスプレイ数式: `$$`...`$$` で囲まれた内容をそのまま `$$`...`$$` で囲んで出力
- MathML は HTML コードを書くのと同様に MathML 記法をそのまま書くことが可能。vfm で特別な処理は不要。
- AsciiMath は、<code>\\'</code>...<code>\\'</code> で囲んで書くことが可能（MathJax での記法は <code>\'</code>...<code>\'</code> だが Markdown ではエスケープが必要）。vfm で特別な処理は不要。

**Comment by yamasy1549** [comment]
> vfm 1.0 では MathJax のみサポートでどうでしょう？

問題ないと思います！

**Comment by akabekobeko** [comment]
本件に対応したいのですが `math: false` ならば

- 数式に関する処理は明示的に無効とする
- 現在、常に実行してる remark-math 処理をやめる

ということでよいでしょうか？それと `math` の指定が VFM オプションと Frontmatter の 2 箇所から指定可能な場合、どちらを優先するか決める必要があります。

Frontmatter へ正式対応した際、`title` でこの検討が発生して、Frontmatter が優先されることにしました。よりコンテンツに近いものを優先するという考えからそうしましたが `math` も踏襲しますか？

**Comment by MurakamiShinyu** [comment]
`math: true` の場合は https://github.com/vivliostyle/vfm/issues/37#issuecomment-813201639 の処理を行う（現在の remark-math 処理はやめる）、`math: false` の場合はその処理を行わない、デフォルトは `math: false`、というのがこの案です。

> Frontmatter が優先されることにしました。よりコンテンツに近いものを優先するという考えからそうしましたが math も踏襲しますか？

はい。原稿により `$`...`$` を数式と解釈されると困る場合があるので、原稿の著者がこの原稿では math を使用しないということを原稿ファイルに指定できることは意味があります。

**Comment by akabekobeko** [comment]
「囲まれた内容をそのまま」というのは

> （現在の remark-math 処理はやめる）

という意図だったのですね。v1.0 としてはこの npm 依存と処理を見送ります。Git には履歴から復旧も可能なので v2.0 で remark-math をどうするか改めて検討しましょう。

構文解析は `remark-math` に頼らず独自処理で `$...$` と `$$...$$` を検出するということでよいでしょうか？その場合、Markdown 的には

- `$...$` インライン
- `$$...$$` インライン
- `$$\n...\n$$` ブロック

が対象ですかね。

> インライン数式: `$`...`$` で囲まれた内容をそのまま（記号類がそのまま出力されること） `\(`...`\)` で囲んで出力

これがよく分からなかったのですが `$...$` があるとして

1. `$` は消して内容を `\(...\)` のように囲む
2. `$` は残して `\($...$\)` のように囲む
3. `$` は残して `$\(...\)$` のように囲む

のいずれでしょうか？

**Comment by MurakamiShinyu** [comment]
> 構文解析は `remark-math` に頼らず独自処理で `$...$` と `$$...$$` を検出するということでよいでしょうか？その場合、Markdown 的には
> 
> * `$...$` インライン
> * `$$...$$` インライン
> * `$$\n...\n$$` ブロック
> 
> が対象ですかね。

`$$...$$` と `$$\n...\n$$` の区別は不要です。すべて Markdown 的にはインラインの扱いでよいでしょう。（インライン数式、ディスプレイ数式のスタイルを分けることはMathJaxがやってくれる）

> 
> > インライン数式: `$`...`$` で囲まれた内容をそのまま（記号類がそのまま出力されること） `\(`...`\)` で囲んで出力
> 
> これがよく分からなかったのですが `$...$` があるとして
> 
> 1. `$` は消して内容を `\(...\)` のように囲む
> 2. `$` は残して `\($...$\)` のように囲む
> 3. `$` は残して `$\(...\)$` のように囲む
> 
> のいずれでしょうか？

1です。MathJaxのデフォルトの設定ではインライン数式の記法は `$...$` ではなくて `\(...\)` であるので、それに合わせて変えるということです。

**Comment by akabekobeko** [comment]
ありがとうございます。インライン `$...$` のみを対象とし、これを検出したら `\(...\)` に変換します。構文以外の HTML 関連は特に疑問もないため、そのまま実装します。

**Comment by MurakamiShinyu** [comment]
「囲まれた内容をそのまま」というのは、囲まれた内容は Markdown の処理をしないでということです。TeX数式は `\` を使うので、それをそのまま書ける必要があります。したがって `$...$` だけでなく `$$...$$` も検出して処理する必要あります。

**Comment by akabekobeko** [comment]
すみません、

> `$$...$$` も検出して処理する必要あります。

というのはこれを検出した場合も `\(...\)` に変換するということでしょうか？仕様としては

1. 1 〜 2 個の一致する `$` で囲まれた範囲を `\(...\)` に変換する = 例: `$...$`, `$$...$$`
2. 1 〜 N 個の一致する `$` で囲まれた範囲を `\(...\)` に変換する = 例: `$...$`, `$$...$$`, `$$$...$$$`, ...etc
3. その他

のいずれになりますか？

またこれを検出した際に囲まれた部分を Markdown 処理しないとして、少なくとも remark の CommonMark/GFM が最初に実行されるのでこれに該当する構文が含まれていた場合は割り込みを検討する必要があります。それが可能であるかは要調査です。

CommonMark/GFM 以後であればルビがそうしているように MDAST で独自 Node に変換すれば後続の Markdown 処理を回避できます。remark 13 を見越して

- https://github.com/akabekobeko/examples-remark-plugin-micromark/blob/main/src/index.ts

こんな感じで実装しようと思います。↑はこの間のイベント登壇で触れた remark へ頼らず MDAST 処理をするサンプルです。

**Comment by MurakamiShinyu** [comment]
> すみません、
> 
> > `$$...$$` も検出して処理する必要あります。
> 
> というのはこれを検出した場合も `\(...\)` に変換するということでしょうか？

`$$...$$` （ディスプレイ数式）は `\(...\)` ではなくて `$$...$$` のままです。

MathJaxのドキュメント:
http://docs.mathjax.org/en/latest/basic/mathematics.html

> The default math delimiters are `$$...$$` and `\[...\]` for displayed mathematics, and `\(...\)` for in-line mathematics. ...

ディスプレイ数式は `$$...$$` のほかに `\[...\]` も可能ですが、入力のままの `$$...$$` を出力にするのがよいと思います。
まとめると:

- `$` で囲まれた範囲を `\(...\)` に変換して出力
- `$$` で囲まれた範囲を`$$` も含めてそのまま出力
- 3個以上連続のドル記号（`$$$` など） については何もしない 
- `$` または `$$` で囲まれた範囲は Markdown 記法が無効であること

**Comment by akabekobeko** [comment]
ありがとうございます。ここまでのやりとりで疑問が解消したので実装してみます。

**Comment by akabekobeko** [comment]
正規表現を検討中。`$...$` のみにヒットして `$$...$$` のように 2 以上の連続を除外したい。

**Comment by akabekobeko** [comment]
手元で実装して動作するところまできたが

> `$` または `$$` で囲まれた範囲は Markdown 記法が無効であること

を実現できていない。MDAST で `text` を `type: 'inlineMath'`、`hName: 'inlineMath'` (`$$` なら `displayMath`) とすれば以降の `text` を対象とした処理から免れると予想していた。remark プラグインでも remark-parse の次にしており CommonMark/GFM は仕方ない (これらは先頭実行となる) としても後続の `ruby` が処理されてしまう。ログ的にも `math` の MDAST 処理が先になっているのを確認済み。

継続調査する。

**Comment by akabekobeko** [comment]
ログ出力すると MDAST 自体は書き換わっている。

```
{
  type: 'paragraph',
  children: [
    { type: 'text', value: 'text' },
    { type: 'displayMath', data: [Object], children: [] },
    { type: 'text', value: 'text' }
  ]
}
```

しかし `Processor.parse()` の返すデータ上は `text` になっていた。

```
0 text "$x=y$"
```

remark-parse の `tokenizeInline` を通した処理と MDAST を直に操作した場合で異なる点があるのだろう。恐らく後者で不足している処理がある。この方向で調べる。

**Comment by akabekobeko** [comment]
mdast-util-find-and-replace に置き換えてもダメだった。処理時点の MDAST は書き換わるが `Processor.parse()` の返すデータには反映されない。そのため他の remark プラグインによって処理されてしまう。

**Comment by akabekobeko** [comment]
独自処理では他の Markdown 構文と排他できない問題があり、どうやらこれは remark に関与しない限り回避できなさそうだ。そのため数式として

1. remark 13 未満の remark-parse が提供する `inlineTokenizers` と `inlineMethods` を実装
2. remark 非依存の MDAST 処理を実装
3. remark-rehype の handler と HAST 処理を実装、これは 1 と 2 で共通 (remark の影響を受けない)

のようにしてみた。インターフェイスを判定して 1 が可能ならそれを、存在しなければ 2 が実行される。

懸念として VFM 1.0 なら 1 により remark-parse の拡張した Unified 機能内で構文は排他されるが、VFM 2.0 で 2 が呼び出された場合はそうならない。数式内に Markdown 構文と解釈可能な部分があるなら処理されてしまう。

ただしこれはルビなどにも言えることで VFM 1.0 としては remark 依存を許容するほうがよいだろう。VFM 2.0 の remark 13 対応時にこの「懸念 = 課題」は改めて検討する。

**Comment by akabekobeko** [comment]
もうひとつの課題。PR の前にドキュメントを書いていて気づいたのだが Frontmatter の `math` は MDAST 時点で処理されるため `false` にしてもオプション側で有効にしていれば数式処理は実行されてしまう。

構文の有無に関する Frontmatter 設定が追加されたので処理の見直しが必要。順番制御にするか Frontmatter だけ前処理するか検討する。

**Comment by akabekobeko** [comment]
記法と出力される HTML の議論を #89 でもおこなっているので、興味のある方はそちらも参考にしてください。

**Comment by akabekobeko** [comment]
1.0.0-alpha.19 にて、ここまで議論された内容を実装しました。その PR #89 コメントにて @MurakamiShinyu さんと @yamasy1549 さんに機能確認いただけたので本件は close します。

もしバグや他の要望がある場合は別途 issue 登録をお願いします。
