### ISSUE TITLE
spec: Markdown inside HTML blocks

### ISSUE THREAD

**Issue by MurakamiShinyu** [vivliostyle/vfm#4]
How to enable markdown inside HTML blocks? There are differences between major Markdown dialects:

- Pandoc Markdown: markdown is enabled by default inside HTML blocks
  - See: [Pandoc Extension: markdown_in_html_blocks](https://pandoc.org/MANUAL.html#extension-markdown_in_html_blocks)
- GFM and CommonMark: markdown is enabled if there is a blank line after the start tag
  - See: [GFM Spec: HTML blocks](https://github.github.com/gfm/#html-blocks)
- PHP Markdown Extra: markdown is enabled if `markdown="1"` is added in the start tag
  - See: [PHP Markdown Extra: Markdown Inside HTML Blocks](https://michelf.ca/projects/php-markdown/extra/#markdown-attr)

I think Pandoc Markdown's method is most useful and easy to understand.

Examples: 

```md
<div class="foo">
* Here, markdown is **enabled** in Pandoc Markdown
</div>
```

```md
<div class="foo">

* Here, markdown is **enabled** in GFM and CommonMark
</div>
```

```md
<div class="foo" markdown="1">
* Here, markdown is **enabled** in PHP Markdown Extra
</div>
```

**Comment by uetchy** [comment]
Consecutive HTML blocks should be treated as plain HTML. Parsing content inside HTML and handling them as Markdown could produce an unwanted effect.

For styled divs with Markdown, use `Fenced blocks` instead.

**Comment by MurakamiShinyu** [comment]
> Consecutive HTML blocks should be treated as plain HTML.

Ok, it will be compatible with GFM and CommonMark, and also default behavior of the remark parser.

**Comment by akabekobeko** [comment]
本件はドキュメントに VFM が CommonMark/GFM のスーパーセットであることを記述することを持って close 予定。

**Comment by akabekobeko** [comment]
すでに `docs/vfm.md` で

> VFM is implemented top on CommonMark and GFM.

と言及されているので close します。結論としては途中のコメントにもありますが現状は GFM 準拠ということになります。

もし GFM と異なる記法 (機能) で対応を希望される場合は、その旨をコメントのうえ Reopen してください。
