### ISSUE TITLE
Change hard line breaks to optional

### ISSUE THREAD

**Issue by akabekobeko** [vivliostyle/vfm#50]
## Goals

Change hard line breaks to optional.

VFM will be based on CommonMark/GFM and will add its own syntax. When overwriting the function of CommonMark/GFM, it is treated as an option. Do not overwrite the function until the option is specified.

## Prior Art

CommonMark/GFM

## Discussion

Discussed and approved in [Developers meeting January 2021](https://github.com/vivliostyle/community/issues/81).

**Comment by akabekobeko** [comment]
#38 の原因と予想される remark-breaks は CommonMark/GFM の挙動を上書きするため、オプション扱いとする予定。

**Comment by akabekobeko** [comment]
オプション案。

- API: `autoBreak: boolean` 既定値は無効で `false` 
- CLI: = `--auto-breaks` 使用頻度は高くなさそうなためショート ハンドは提供しない

現行の実装では `rehive-parse.ts` にて MDAST 系を静的に定義しているが、オプションにより構成を変更可能とするように設計変更する必要がある。

**Comment by akabekobeko** [comment]
#59 対応により `buildProcessorTestingCode` へ VFM オプションを渡せるようになったので改行の `<br>` 変換を想定したコードでは本 issue 対応時に必ず指定すること。

**Comment by MurakamiShinyu** [comment]
オプション案の修正案 (See: https://github.com/vivliostyle/vfm/pull/64#issuecomment-762961582):
- API: `hardLineBreaks`
- CLI: `--hard-line-breaks`

**Comment by akabekobeko** [comment]
村上さん案を #64 に採用しました。`v1.0.0-alpha.16` にて反映予定です
