### ISSUE TITLE
Command line option "-r" in help should be "-p"

### ISSUE THREAD

**Issue by MurakamiShinyu** [vivliostyle/vfm#56]
## Issue Details

- VFM version
  - 1.0.0-alpha.15

```
$  vfm --help
... 
  Options
    --style, -s    Custom stylesheet path/URL
    --partial, -r  Output markdown fragments
    --title        Document title (ignored in partial mode)
    --language     Document language (ignored in partial mode)
```

これらのオプションのうち、 `-r` が機能しません。長い名前の `--partial` は機能します。
ソースコードを見たところ、 `-r` は `-p` の間違いのようです。
https://github.com/vivliostyle/vfm/blob/5ca4c71d40f75ba1e5df3f8ae0d24dbd65fd8d2b/src/cli.ts#L16-L33

**Comment by akabekobeko** [comment]
ヘルプ文字列を間違えているだけなので v1.0 として対応します。

**Comment by akabekobeko** [comment]
修正しました。VFM v1.0.0-alpha.16 に反映される予定です。
